### ISSUE TITLE
Use of signature is not thread-safe

### ISSUE THREAD

**Issue by initdch** [admin-ch/CovidCertificate-Signing-Service#1]
It seems the use of Signature in the CryptoController is not thread-safe and parallel request could result in wrong signatures to be returned to the caller.

The Signature is initialized as a Singleton bean in 
https://github.com/admin-ch/CovidCertificate-Signing-Service/blob/bb7af927367a7fd90f3b69e6777c32030de07a99/src/main/java/ch/admin/bag/covidcertificate/signature/config/HsmConfig.java#L63

So the signature is shared between all the requests and this could lead to wrong requests or a SignatureException when the update message has been reset by another call. [Signature (JDK 11)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/Signature.html#sign())
https://github.com/admin-ch/CovidCertificate-Signing-Service/blob/bb7af927367a7fd90f3b69e6777c32030de07a99/src/main/java/ch/admin/bag/covidcertificate/signature/web/controller/CryptoController.java#L23-L24

**Comment by Quietghost** [comment]
Thanks for the input, we are looking into it.

**Comment by delixfe** [comment]
@initdch  See 7ed8bc3f03e251fde6b81932258d628bef2b08dc.

**Comment by initdch** [comment]
Perfect. Thanks 👍
